/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 corgi.gltf --transform 
Files: corgi.gltf [3.76MB] > C:\Users\User\Downloads\porfolio stuff\astro_corgi\corgi-transformed.glb [1.88MB] (50%)
Author: CzernO (https://sketchfab.com/czernobog)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/astro-corgi-f958b29707e84605bed930d52ecab470
Title: Astro Corgi
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/corgi-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.geometry_3_geometry_3_0.geometry} material={materials.geometry_3} scale={0.01} />
    </group>
  )
}

useGLTF.preload('/corgi-transformed.glb')
